version: 2

jobs:
    autogen:
        docker:
            - image: xenos1984/cross-tools:latest
        working_directory: ~/nos/source
        steps:
            - checkout
            - run: rm -rf .git
            - run: ./autogen.sh
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - source
            - run: "wget --method=PATCH --user=xenos1984 --password=$GHTOKEN --body-data=\{\"sha\":\"${CIRCLE_SHA1}\"\} -O - https://api.github.com/repos/xenos1984/nos/git/refs/tags/latest"
            - run:
                name: IRC notify
                command: ~/nos/source/.circleci/irc.sh
                when: always

    build_i686:
        docker:
            - image: xenos1984/cross-i686-pc-elf:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_pc.sh i686-pc-elf mp-acpi
            - run: .circleci/build_pc.sh i686-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_pc.sh i686-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_pc.sh i686-pc-elf sp-noacpi --disable-smp --disable-acpi
            - run: .circleci/pc_multi_iso.sh i686-pc-elf
            - run: "wget --method=POST --user=xenos1984 --password=$GHTOKEN --header='Content-Type: application/octet-stream' --body-file=../i686-pc-elf/NOS.iso -O - \"https://uploads.github.com/repos/xenos1984/NOS/releases/9063364/assets?name=nos-i686.iso&label=NOS%20bootable%20ISO%20%2Ei686%2F\""
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - i686-pc-elf

    build_x86_64:
        docker:
            - image: xenos1984/cross-x86_64-pc-elf:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_pc.sh x86_64-pc-elf mp-acpi
            - run: .circleci/build_pc.sh x86_64-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_pc.sh x86_64-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_pc.sh x86_64-pc-elf sp-noacpi --disable-smp --disable-acpi
            - run: .circleci/pc_multi_iso.sh x86_64-pc-elf
            - run: "wget --method=POST --user=xenos1984 --password=$GHTOKEN --header='Content-Type: application/octet-stream' --body-file=../x86_64-pc-elf/NOS.iso -O - \"https://uploads.github.com/repos/xenos1984/NOS/releases/9063364/assets?name=nos-x86_64.iso&label=NOS%20bootable%20ISO%20%2Ex86_64%2F\""
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - x86_64-pc-elf

    build_raspi2:
        docker:
            - image: xenos1984/cross-arm-raspi2-eabi:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_raspi.sh arm-raspi2-eabi mp
            - run: .circleci/build_raspi.sh arm-raspi2-eabi sp --disable-smp
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - arm-raspi2-eabi

    qemu_i686:
        docker:
            - image: xenos1984/test-qemu:latest
        working_directory: ~/nos/i686-pc-elf
        steps:
            - attach_workspace:
                at: ~/nos
            - run:
                name: QEMU (32 bit, 1 CPU, ISA PC; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 isapc 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, ISA PC; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 isapc 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, ISA PC; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 isapc 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, ISA PC; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 isapc 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, i440FX + PIIX; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, i440FX + PIIX; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, i440FX + PIIX; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, i440FX + PIIX; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, Q35 + ICH9; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, Q35 + ICH9; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, Q35 + ICH9; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 1 CPU, Q35 + ICH9; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, i440FX + PIIX; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 4 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, i440FX + PIIX; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 4 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, i440FX + PIIX; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 4 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, i440FX + PIIX; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 pc 4 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, Q35 + ICH9; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 4 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, Q35 + ICH9; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 4 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, Q35 + ICH9; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 4 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (32 bit, 4 CPUs, Q35 + ICH9; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh i386 q35 4 sp-noacpi
                no_output_timeout: 60s
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - i686-pc-elf/mp-acpi/qemu*
                    - i686-pc-elf/mp-noacpi/qemu*
                    - i686-pc-elf/sp-acpi/qemu*
                    - i686-pc-elf/sp-noacpi/qemu*
            - run:
                name: IRC notify
                command: ~/nos/source/.circleci/irc.sh
                when: always

    qemu_x86_64:
        docker:
            - image: xenos1984/test-qemu:latest
        working_directory: ~/nos/x86_64-pc-elf
        steps:
            - attach_workspace:
                at: ~/nos
            - run:
                name: QEMU (64 bit, 1 CPU, ISA PC; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 isapc 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, ISA PC; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 isapc 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, ISA PC; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 isapc 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, ISA PC; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 isapc 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, i440FX + PIIX; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, i440FX + PIIX; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, i440FX + PIIX; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, i440FX + PIIX; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, Q35 + ICH9; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 1 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, Q35 + ICH9; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 1 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, Q35 + ICH9; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 1 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 1 CPU, Q35 + ICH9; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 1 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, i440FX + PIIX; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 4 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, i440FX + PIIX; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 4 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, i440FX + PIIX; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 4 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, i440FX + PIIX; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 pc 4 sp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, Q35 + ICH9; MP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 4 mp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, Q35 + ICH9; MP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 4 mp-noacpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, Q35 + ICH9; SP, ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 4 sp-acpi
                no_output_timeout: 60s
            - run:
                name: QEMU (64 bit, 4 CPUs, Q35 + ICH9; SP, no ACPI)
                command: ~/nos/source/.circleci/qemu_pc.sh x86_64 q35 4 sp-noacpi
                no_output_timeout: 60s
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - x86_64-pc-elf/mp-acpi/qemu*
                    - x86_64-pc-elf/mp-noacpi/qemu*
                    - x86_64-pc-elf/sp-acpi/qemu*
                    - x86_64-pc-elf/sp-noacpi/qemu*
            - run:
                name: IRC notify
                command: ~/nos/source/.circleci/irc.sh
                when: always

    qemu_raspi2:
        docker:
            - image: xenos1984/test-qemu:latest
        working_directory: ~/nos/arm-raspi2-eabi
        steps:
            - attach_workspace:
                at: ~/nos
            - run:
                name: QEMU raspi2 MP
                command: ~/nos/source/.circleci/qemu_raspi.sh mp
                no_output_timeout: 60s
            - run:
                name: QEMU raspi2 SP
                command: ~/nos/source/.circleci/qemu_raspi.sh sp
                no_output_timeout: 60s
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - arm-raspi2-eabi/mp/qemu*
                    - arm-raspi2-eabi/sp/qemu*
            - run:
                name: IRC notify
                command: ~/nos/source/.circleci/irc.sh
                when: always

    collect:
        docker:
            - image: xenos1984/cross-tools:latest
        working_directory: ~/nos
        steps:
            - attach_workspace:
                at: ~/nos
            - store_artifacts:
                path: ~/nos/i686-pc-elf
                destination: i686-pc-elf
            - store_artifacts:
                path: ~/nos/x86_64-pc-elf
                destination: x86_64-pc-elf
            - store_artifacts:
                path: ~/nos/arm-raspi2-eabi
                destination: arm-raspi2-eabi
            - run:
                name: IRC notify
                command: ~/nos/source/.circleci/irc.sh
                when: always

workflows:
    version: 2
    build:
        jobs:
            - autogen
            - build_i686:
                requires:
                    - autogen
            - build_x86_64:
                requires:
                    - autogen
            - build_raspi2:
                requires:
                    - autogen
            - qemu_i686:
                requires:
                    - build_i686
            - qemu_x86_64:
                requires:
                    - build_x86_64
            - qemu_raspi2:
                requires:
                    - build_raspi2
            - collect:
                requires:
                    - qemu_i686
                    - qemu_x86_64
                    - qemu_raspi2

