version: 2

jobs:
    autogen:
        docker:
            - image: xenos1984/cross-source:latest
        working_directory: ~/nos/source
        steps:
            - checkout
            - run: ./autogen.sh
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - source

    build_i686:
        docker:
            - image: xenos1984/cross-i686-pc-elf:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_pc.sh i686-pc-elf mp-acpi
            - run: .circleci/build_pc.sh i686-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_pc.sh i686-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_pc.sh i686-pc-elf sp-noacpi --disable-smp --disable-acpi
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - i686-pc-elf

    build_x86_64:
        docker:
            - image: xenos1984/cross-x86_64-pc-elf:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_pc.sh x86_64-pc-elf mp-acpi
            - run: .circleci/build_pc.sh x86_64-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_pc.sh x86_64-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_pc.sh x86_64-pc-elf sp-noacpi --disable-smp --disable-acpi
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - x86_64-pc-elf

    build_raspi2:
        docker:
            - image: xenos1984/cross-arm-raspi2-eabi:latest
        working_directory: ~/nos/source
        steps:
            - attach_workspace:
                at: ~/nos
            - run: .circleci/build_raspi.sh arm-raspi2-eabi mp
            - run: .circleci/build_raspi.sh arm-raspi2-eabi sp --disable-smp
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - arm-raspi2-eabi

    qemu_raspi2:
        docker:
            - image: xenos1984/test-qemu:latest
        working_directory: ~/nos/arm-raspi2-eabi
        steps:
            - attach_workspace:
                at: ~/nos
            - run:
                name: QEMU raspi2 MP
                command: ~/nos/source/.circleci/qemu_raspi.sh mp
                no_output_timeout: 60s
            - run:
                name: QEMU raspi2 SP
                command: ~/nos/source/.circleci/qemu_raspi.sh sp
                no_output_timeout: 60s
            - persist_to_workspace:
                root: ~/nos
                paths:
                    - arm-raspi2-eabi/mp/qemu.txt
                    - arm-raspi2-eabi/sp/qemu.txt

    collect:
        docker:
            - image: xenos1984/cross-source:latest
        working_directory: ~/nos
        steps:
            - attach_workspace:
                at: ~/nos
            - store_artifacts:
                path: ~/nos/i686-pc-elf
                destination: i686-pc-elf
            - store_artifacts:
                path: ~/nos/x86_64-pc-elf
                destination: x86_64-pc-elf
            - store_artifacts:
                path: ~/nos/arm-raspi2-eabi
                destination: arm-raspi2-eabi

workflows:
    version: 2
    build:
        jobs:
            - autogen
            - build_i686:
                requires:
                    - autogen
            - build_x86_64:
                requires:
                    - autogen
            - build_raspi2:
                requires:
                    - autogen
            - qemu_raspi2:
                requires:
                    - build_raspi2
            - collect:
                requires:
                    - build_i686
                    - build_x86_64
                    - build_raspi2
                    - qemu_raspi2

