version: 2

jobs:
    autogen:
        docker:
            - image: xenos1984/cross-source:latest
        working_directory: ~/nos
        steps:
            - checkout
            - run: ./autogen.sh
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: nos-source-{{ checksum ".circle-sha" }}
                paths:
                    - ~/nos

    build_i686:
        docker:
            - image: xenos1984/cross-i686-pc-elf:latest
        working_directory: ~/nos
        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - nos-source-{{ checksum ".circle-sha" }}
            - run: .circleci/build_x86.sh i686-pc-elf mp-acpi
            - run: .circleci/build_x86.sh i686-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_x86.sh i686-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_x86.sh i686-pc-elf sp-noacpi --disable-smp --disable-acpi
            - save_cache:
                key: nos-i686-pc-elf-{{ checksum ".circle-sha" }}
                paths:
                    - ~/i686-pc-elf

    build_x86_64:
        docker:
            - image: xenos1984/cross-x86_64-pc-elf:latest
        working_directory: ~/nos
        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - nos-source-{{ checksum ".circle-sha" }}
            - run: .circleci/build_x86.sh x86_64-pc-elf mp-acpi
            - run: .circleci/build_x86.sh x86_64-pc-elf mp-noacpi --disable-acpi
            - run: .circleci/build_x86.sh x86_64-pc-elf sp-acpi --disable-smp
            - run: .circleci/build_x86.sh x86_64-pc-elf sp-noacpi --disable-smp --disable-acpi
            - save_cache:
                key: nos-x86_64-pc-elf-{{ checksum ".circle-sha" }}
                paths:
                    - ~/x86_64-pc-elf

    collect:
        docker:
            - image: xenos1984/cross-source:latest
        working_directory: ~/nos
        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - nos-i686-pc-elf-{{ checksum ".circle-sha" }}
            - restore_cache:
                keys:
                    - nos-x86_64-pc-elf-{{ checksum ".circle-sha" }}
            - store_artifacts:
                path: ~/i686-pc-elf
                destination: i686-pc-elf
            - store_artifacts:
                path: ~/x86_64-pc-elf
                destination: x86_64-pc-elf

workflows:
    version: 2
    build:
        jobs:
            - autogen
            - build_i686:
                requires:
                    - autogen
            - build_x86_64:
                requires:
                    - autogen
            - collect:
                requires:
                    - build_i686
                    - build_x86_64

